cmd/server/main.go, elasticsearch.go, elasticsearch_test.go, go.mod, version.go
This can be used for tests and in a standalone type mode (where Docker is on the host).
=> elasticsearch: add basic setup to launch an ES docker image

cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
`Jane Doe` matching `jan lahore` at 81% seemed a bit high, let's ignore the spaces.
=> cmd/server: search: don't include spaces in jaroWrinkler distance 

.travis.yml, makefile
Cross-Compiling with sqlite is pretty annoying, so let's just try
building and releasing from each OS since TravisCI supports that.
Issue: https://github.com/moov-io/docs/issues/27
=> build: release binaries from each platform

cmd/server/http.go, cmd/server/http_test.go
Previously, OFAC was reporting metrics like:
```
{app="ofac",route="get-companies-17042"}
{app="ofac",route="delete-companies-21206-watch-ce5bb48f9a36320c27ad2062c595bb2bcba0c658"}
```
These metrics make aggregations a lot less performant and we really want route="get-companies" as the Prometheus label.
=> cmd/server: cleanup HTTP Prometheus metric labels

client/docs/UpdateCompanyStatus.md, client/docs/UpdateCustomerStatus.md, client/model_update_company_status.go, client/model_update_customer_status.go, openapi.yaml
I realized this wasn't in the API docs after Wade mentioned needing this ability in OFAC.
=> api: add missing 'notes' field on UpdateCompanyStatus and UpdateCustomerStatus

client/api_ofac.go, client/docs/OFACApi.md, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, openapi.yaml
When a search request contains `?address=..&country=..` we will compute the average match percent between an Address against both compare functions and rank all results accordingly.
Issue: https://github.com/moov-io/ofac/issues/79
=> cmd/server: search: handle Country and average weight with Address

cmd/server/sqlite.go, go.mod, go.sum
This PR adds a setup for migrating tables to add columns. The more popular [golang-migrate/migrate](https://github.com/golang-migrate/migrate) seems pretty complicated for migrations (and wants to require several external tools, go-bindata and their CLI tool). Instead [lopezator/migrator](https://github.com/lopezator/migrator) still keeps a versioned table (to only run migrations once) and allows us to embed migrations in source code. 
Project: https://github.com/lopezator/migrator
=> cmd/server: create setup for adding colums to a database table

cmd/server/download_handler.go, cmd/server/download_handler_test.go
Issue: https://github.com/moov-io/ofac/issues/98
=> cmd/server: rename manual refresh endpoint to /data/refresh

README.md, cmd/server/download.go, cmd/server/download_handler.go, cmd/server/download_test.go, cmd/server/main.go, cmd/server/search_test.go, download.go, download_test.go
From reading the environment variable INITIAL_DATA_DIRECTORY OFAC checks for files to use as the initial data source until a periodic refresh is executed.
Issue: https://github.com/moov-io/ofac/issues/112
=> download: check for initial files on first refresh

README.md, cmd/server/download.go, cmd/server/download_test.go, cmd/server/main.go, download.go, download_test.go
Disabling this allows users to have more control of when data is updated. 
Issue: https://github.com/moov-io/ofac/issues/112
=> cmd/server: disable perioidic refresh via OFAC_DATA_REFRESH=off

client/api/openapi.yaml, client/api_ofac.go, client/docs/OFACApi.md, cmd/server/filter.go, cmd/server/filter_test.go, cmd/server/search_handlers.go, openapi.yaml
Various compliance assessments of OFAC data require filtering around
the government program this data is associated with or to be more
specific about the SDN's type (aircraft vs individual).
Fixes: #133
=> cmd/server: accept additional query params to filter SDN search results

CHANGELOG.md, cmd/server/filter.go, cmd/server/main.go, cmd/server/values.go, cmd/server/values_test.go
UI applications (web pages, dropdowns, etc) often are more useful to the user if they can show possible values for a column. This change adds an endpoint for doing exactly that:
```
GET /ui/values/sdnType
```
This would return:
```
["aircraft","individual","vessel"]
```
Also, `?limit=2` is supported with a default of 10 and max of 100 (just like search results). 
Edit: This endpoint would be used with the [recently added filter](https://github.com/moov-io/ofac/pull/134) query parameters (and to pre-fill the UI). 
Examples: https://gist.github.com/adamdecaf/6d9ec68dbce0308695057953dc38a0a2
=> cmd/server: add endpoint for applications to grab distinct sets of column values

webui/package.json, webui/src/App.js, webui/src/Form/index.js, webui/src/__tests__/utils.tests.js, webui/src/utils.js
We want the ability to save/share webui URLs that include search criteria.
When the app loads, it will parse any criteria in the url, populate search fields and immediately execute a search. The URL is updated with current criteria anytime a search or reset is executed.
=> webui: sync url and search state

client/api/openapi.yaml, client/api_ofac.go, client/docs/OFACApi.md, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, openapi.yaml
Often SDN remarks will contain government ID values which are unique
to that entity. This can be a really strong signal so we need to allow
clients to query based on those values.
Issue: #141
=> cmd/server: add /search?id=NNN endpoint for matching remark IDs

cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
We should favor strong single word matches to reflect higher overall
match percentages. In short this is useful for matching names like:
Nicolas MADURO
against an SDN entity like:
MADURO MOROS, Nicolas
People often won't specify middle names (or multiple first/last
names), so when positive matches are identified we should keep the
overall match percentages high.
Issue: #141
=> cmd/server: adjust jaro weighting to maximize total weight in strong single word matches

cmd/server/download_handler.go, cmd/server/search_handlers.go
We already specify a logger in tests so these are wasteful.
=> cmd/server: remove 'logger != nil' checks

webui/src/App.js, webui/src/Components.js, webui/src/Form/index.js, webui/src/Results/Addresses.js, webui/src/Results/AltNames.js, webui/src/Results/SDNDetails.js, webui/src/Results/index.js, webui/src/api.js
Includes:
- fix the parameter name passed to the search api `type` => `sdnType`
- polish the search interaction with a loading state and error display
- when expanding SDN results, show the `addressID` / `alternateID` rather than duplicate the parent `entityID`
=> Search api lifecycle

client/api/openapi.yaml, client/docs/Search.md, client/model_search.go, cmd/server/download.go, cmd/server/download_test.go, cmd/server/search.go, cmd/server/search_handlers.go, openapi.yaml
This was requested as part of an audit of OFAC, which helps clients to
know how stale the data being searched on is.
=> cmd/server: return the oldest refresh time for our data in search results

CHANGELOG.md, cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_test.go
Found this during https://github.com/moov-io/ofac/pull/148 testing. Some addresses from the SDN file have partial data (missing address, city/state/providence, or zip fields).
=> cmd/server: never allow jaroWinkler to return NaN

cmd/internal/client.go, cmd/internal/client_test.go, cmd/ofaccheck/main.go, cmd/ofactest/main.go, makefile, test/testdata/allowed.txt, test/testdata/blocked.txt
```
ofaccheck is a cli tool used for testing batches of names against Moov's OFAC service.
With no arguments the contaier runs tests against the production API, but we strongly ask you
run ofaccheck against local instances of OFAC.
$ ofaccheck -allowed-file users.txt -blocked-file criminals.txt -threshold 0.99 -sdn-type individual -v
2019/10/09 17:36:16.160025 main.go:61: Starting moov/ofaccheck v0.12.0-dev
2019/10/09 17:36:16.160055 main.go:64: [INFO] using http://localhost:8084 for address
2019/10/09 17:36:16.161818 main.go:73: [SUCCESS] ping
2019/10/09 17:36:16.174108 main.go:156: [INFO] didn't block 'Husein HAZEM'
2019/10/09 17:36:16.212986 main.go:148: [INFO] blocked 'Nicolas Ernesto MADURO GUERRA'
2019/10/09 17:36:16.213423 main.go:146: [ERROR] 'Maria Alexandra PERDOMO' wasn't …
```
=> cmd/ofaccheck: initial setup of a cli tool for batch searches

pkg/dpl/reader.go, pkg/dpl/reader_test.go
I noticed this comes up from DPL's list, whoops.
=> pkg/dpl: ignore first line of header information

cmd/server/debug_sdn.go, cmd/server/debug_sdn_test.go, cmd/server/main.go, cmd/server/search.go
We're including several steps between parsing the agencies file and what results are returned for a query. To help debugging we're adding a route for SDN entries to show their unexported fields (indexed name, remarks id, etc). 
With lists that have unique ids for each entry this type of route works great, but not every list offers that.
=> cmd/server: add admin route to debug indexed SDN information

README.md, cmd/server/issue326_test.go, cmd/server/search.go
This is the fist configuration option available to tweak match results which should help specific use-cases. Various entity names are better handled with a single word match. 
This change does allow match percentages to be above 100% now as the weighting isn't bounded. 
Issue: https://github.com/moov-io/watchman/issues/326
=> search: introduce EXACT_MATCH_FAVORITISM config to optionally boost match rates

cmd/server/pipeline_normalize_test.go
```
Running tool: /usr/local/bin/go test -timeout 30s -run ^TestPrecompute$ github.com/moov-io/watchman/cmd/server
ok  	github.com/moov-io/watchman/cmd/server	0.175s
```
=> update TestPrecompute to modern standards

cmd/server/filter.go, cmd/server/filter_test.go, cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_async.go, cmd/server/search_benchmark_test.go, cmd/server/search_handlers.go, cmd/server/search_test.go
Let's pass a closure through to exclude results prior to accumulation. This allows us to return more accurate results.
Issue: https://github.com/moov-io/watchman/issues/349
=> cmd/server: filter as part of searching, not after the fact

api/client.yaml, client/api/openapi.yaml, client/docs/BisEntities.md, client/docs/Ssi.md, client/model_bis_entities.go, client/model_ssi.go
- Added **match** to both `SectoralSanctions` and `BisEntities` in the client responses
- Currently both `SectorialSanctions` and `BisEntities` populate match in the service, but are not received when using the api client
- Adding these in allow consumers of the client to get the **match** data on a request
=> COR-462 Add match to client entities

CHANGELOG.md, cmd/server/pipeline.go, cmd/server/pipeline_stopwords.go, cmd/server/pipeline_stopwords_test.go, cmd/server/search_handlers_test.go, version.go
- Updated `stopwordsStep.apply` to remove stopwards for an alt name
- Added in unit tests to confirm `stopwordsStep.apply`
- There was a small bug identified in the previous Pull request which actually prevented alt names from being pre-computed
- Properly confirmed debug logs to confirm alt names are being updated
- Confirmed via UI that results are now lower as expected
=> COR-643 Bugfix on alt names pre-compute

pkg/csl/reader.go, pkg/dpl/reader.go, pkg/dpl/reader_test.go, pkg/ofac/reader.go
Every now and then a source file downloaded from sanctions sources contains a malformed row. This change ensures such a row doesn't cause Watchman to crash. Instead, malformed rows are skipped and the `Read()` functions will just move onto the next row.
=> File Parsing: Skip malformed CSV Rows

.github/workflows/go.yml, makefile
I found this action recently and think it can help split up Go tests by running them in parallel but separate from each other. 
See: https://github.com/hashicorp-forge/go-test-split-action
Edit: We're seeing a major improvement in tests. From 16mins to 5mins. 
Before: https://github.com/moov-io/watchman/actions/runs/4076502797
After: https://github.com/moov-io/watchman/actions/runs/4077961811
=> build: try using hashicorp-forge/go-test-split-action to speedup tests

cmd/server/search_async.go
With some queries the top 5 SDNs wouldn't include a valid result. Instead we need to filter before limiting results.
=> fix: filter SDNs in async search rather than truncate

cmd/server/pipeline_company_name_cleanup_test.go, cmd/server/pipeline_normalize_test.go, cmd/server/pipeline_reorder_test.go, cmd/server/pipeline_stopwords.go, cmd/server/pipeline_stopwords_test.go, cmd/server/pipeline_test.go
An issue noted that "11420 CORP" was being indexed as "corp" with the numbers removed. This is inaccurate as the numbers of a name are valuable.
Fixes: https://github.com/moov-io/watchman/issues/483
=> fix: keep numbers during stopwords step

docs/intro.md
The current URL is a 404 page -- I think the ofac treasury website updated their FAQ.
=> Update URL for OFAC Search Explanation

cmd/server/issue115_test.go, cmd/server/issue326_test.go, cmd/server/search.go, cmd/server/search_eu_csl_test.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, cmd/server/search_us_csl_test.go
Terms are more equal the closer they are in length, so favor closer length terms.
=> cmd/server: weight term score by length similarity

api/client.yaml, cmd/server/largest.go, cmd/server/search_eu_csl_test.go, cmd/server/search_generic.go, cmd/server/search_handlers_test.go, cmd/server/search_uk_csl_test.go, cmd/server/search_us_csl_test.go
`matchedName` is populated with the highest scoring term from the search query.
=> feat: return matchedName in non-OFAC results

README.md, cmd/server/issue115_test.go, cmd/server/new_algorithm_test.go, cmd/server/search.go, cmd/server/search_eu_csl_test.go, cmd/server/search_generic.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, cmd/server/search_us_csl_test.go
This is a re-write of the `jaroWinkler` function with the goal of improving the scoring performance. The new algorithm changes several things:
1. Compare tokens in the search to the index tokens
- i.e. "find matches for every search token" rather than "find match for every indexed token"
- Improves scores of searches that don't include "middle" names
- Prevents sanctioned names that are 1 word (HADI, EMMA, KAMILA) matching long searches
- Has a side-effect that short search terms will have more false positives. I think this is a good trade off as the sanction lists will always contain the full name, but the search might not
2. Once a token has matched something, it can't match a different token
- This prevents names with repeated words having artificially high scores
- e.g. prevents any …
=> Experimental Improved Search Algorithm

cmd/server/download.go, cmd/server/search_crypto_test.go, cmd/server/search_handlers_bench_test.go, cmd/server/search_us_csl.go, go.mod, pkg/csl/csl_test.go, pkg/csl/download.go, pkg/csl/download_eu.go, pkg/csl/download_eu_test.go, pkg/csl/download_test.go, pkg/csl/download_uk.go, pkg/csl/download_uk_test.go, pkg/csl/reader.go, pkg/csl/reader_eu.go, pkg/csl/reader_eu_test.go, pkg/csl/reader_test.go, pkg/csl/reader_uk.go, pkg/csl/reader_uk_test.go, pkg/download/client.go, pkg/dpl/download.go, pkg/dpl/download_test.go, pkg/dpl/reader.go, pkg/dpl/reader_test.go, pkg/ofac/download.go, pkg/ofac/download_test.go, pkg/ofac/reader.go, pkg/ofac/reader_test.go
- before each list Downloader was creating temporary with files on disk that were subsequently read in by the list Parser
- this changes this "communication" to io.ReadCloser which is more ideomatic in Go
- fixes #536 as no temporary files clutter the disk any more
=> pass io.ReadCloser instances instead of files on harddrive, fixes #536

cmd/server/download.go, pkg/download/client.go
Workaround panic from nil dereference in error case
fixes **regression** in v0.28.1
=>   Download all files if the initial dir does not exist. fixes #538

README.md, cmd/server/main.go
Adds a configuration to disable in-browser search for an API only workflow.
=> feat: Add environment configuration to disable Web UI

internal/search/api_search.go, internal/search/api_search_test.go, pkg/csl_us/mapper.go, pkg/ofac/mapper.go, pkg/search/similarity_address.go, pkg/search/similarity_address_test.go
Each .Country field in a query can be normalized before search and each index's .Country can be normalized in the mapper.
<details>
<summary>Benchmarks</summary>
```
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
│ ./pkg/search/before.txt │        ./pkg/search/after.txt        │
│         sec/op          │    sec/op     vs base                │
API_Search/normal-16                         23.65m ± ∞ ¹   23.36m ± ∞ ¹       ~ (p=1.000 n=1) ²
API_Search/debug-16                          65.77m ± ∞ ¹   50.99m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/1-16                83.87m ± ∞ ¹   72.03m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/3-16                33.34m ± ∞ ¹   31.47m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/5-16                25.91m ± ∞ ¹ …
```
=> fix: normalize Country once

internal/postalpool/client.go, internal/postalpool/config.go, internal/postalpool/config_test.go, internal/postalpool/testdata/configs/config.default.yml
```
goos: darwin
goarch: amd64
pkg: github.com/moov-io/watchman/internal/postalpool
cpu: Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
│ ./internal/postalpool/before.txt │ ./internal/postalpool/after.txt │
│              sec/op              │    sec/op     vs base           │
_PostalPool-16                       76.08µ ± ∞ ¹   55.66µ ± ∞ ¹  ~ (p=1.000 n=1) ²
Improvement: ~26.8% faster
│ ./internal/postalpool/before.txt │ ./internal/postalpool/after.txt  │
│               B/op               │     B/op       vs base           │
_PostalPool-16                      18.75Ki ± ∞ ¹   14.46Ki ± ∞ ¹  ~ (p=1.000 n=1) ²
Improvement: ~22.9% less memory
│ ./internal/postalpool/before.txt │ ./internal/postalpool/after.txt │
│            allocs/op             │  allocs/op    vs base           │ …
```
=> postalpool: better pooling by default, offer configurable knobs

cmd/server/config.go, cmd/server/download_test.go, cmd/server/main.go, configs/config.default.yml, internal/search/api_search_test.go, internal/search/config.go, internal/search/service.go, internal/search/service_test.go
With GOMAXPROCS=2
Image: `moov/watchman:dev-b49f05f`
This should result in more stable (less of a long tail) in search performance.
<details>
<summary>Local Benchmarks</summary>
```
│  before.txt  │              after.txt               │
│    sec/op    │    sec/op     vs base                │
API_Search/normal-2              21.44m ± ∞ ¹   21.18m ± ∞ ¹       ~ (p=1.000 n=1) ²
API_Search/debug-2               130.3m ± ∞ ¹   136.9m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/1-2     44.78m ± ∞ ¹   57.62m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/3-2     28.13m ± ∞ ¹   33.17m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/5-2     24.95m ± ∞ ¹   27.29m ± ∞ ¹       ~ (p=1.000 n=1) ²
_Search/fixed_group_size/10-2    24.33m ± ∞ ¹   24.17m ± ∞ ¹       ~ (p=1.000 …
```
=> search: cap groupsize workers by NumCPU / GOMAXPROCS

cmd/server/download_test.go, internal/cslustest/cslustest.go, internal/download/download.go, internal/fshelp/fshelp.go, internal/fshelp/fshelp_test.go, internal/ofactest/ofactest.go, internal/search/service_test.go, pkg/download/client.go
This should reduce the overall time taken for tests (by downloading less files) and keep them more stable on CI.
=> fix: set INITIAL_DATA_DIRECTORY better in tests
