moov-io/watchman

download.go, download_test.go
Same PR as https://github.com/moov-io/ofac/pull/7, but going straight onto master with CI.
=> ofac: Add file downloader for OFAC files

.travis.yml, reader.go
=> remove unneeded stubs

cmd/server/download_test.go, cmd/server/main.go, download.go, download_test.go, elasticsearch.go, elasticsearch_test.go, reader.go
Issue: https://github.com/moov-io/ofac/issues/20
=> cmd/server: download OFAC data and start Elasticsearch concurrently

cmd/server/search.go, cmd/server/search_test.go
Fixes: https://github.com/moov-io/ofac/issues/26
=> cmd/server: read limit query param (with hard max)

cmd/server/customers.go, cmd/server/customers_test.go, cmd/server/search.go, cmd/server/search_test.go
From https://github.com/moov-io/ofac/pull/30 
Issue: https://github.com/moov-io/ofac/issues/19
=>  cmd/server: match up req/resp to OpenAPI docs

cmd/server/customers.go, cmd/server/customers_test.go, cmd/server/main.go, cmd/server/sdn.go, cmd/server/sdn_test.go, cmd/server/search.go
Issue: https://github.com/moov-io/ofac/issues/21
=> cmd/server: stop hardcoding search results and scan OFAC data lists

cmd/server/download.go, cmd/server/download_handler.go, cmd/server/download_handler_test.go, cmd/server/download_test.go, cmd/server/main.go, cmd/server/sqlite.go
Issue: https://github.com/moov-io/ofac/issues/36
=>  cmd/server: record download stats and GET /downloads endpoint

README.md, cmd/server/customers.go, cmd/server/download.go, cmd/server/main.go, cmd/server/search.go, cmd/server/search_async.go, cmd/server/search_async_test.go, cmd/server/search_handlers.go, cmd/server/search_test.go, cmd/server/watch.go, cmd/server/watch_test.go, cmd/server/webhook.go, cmd/server/webhook_test.go, go.mod, go.sum, vendor/go4.org/AUTHORS, vendor/go4.org/LICENSE, vendor/go4.org/syncutil/gate.go, vendor/go4.org/syncutil/group.go, vendor/go4.org/syncutil/once.go, vendor/go4.org/syncutil/sem.go, vendor/go4.org/syncutil/syncutil.go, vendor/modules.txt
Issue: https://github.com/moov-io/ofac/issues/34
=> cmd/server: setup async searching and webhooks 

cmd/server/main.go, cmd/server/search_async.go, cmd/server/sqlite.go, cmd/server/webhook.go, cmd/server/webhook_test.go
Issue: https://github.com/moov-io/ofac/issues/34
=> cmd/server: record webhook stats and timestamp

.travis.yml, Dockerfile-example, example/main.go, example/webhook.go, example/webhook_test.go, makefile
Fixes: https://github.com/moov-io/ofac/issues/43
=> example: add sample Go webhook

README.md, client/docs/WatchRequest.md, client/model_watch_request.go, cmd/server/customers.go, cmd/server/customers_test.go, cmd/server/search_async.go, cmd/server/sqlite.go, cmd/server/watch.go, cmd/server/watch_test.go, cmd/server/webhook.go, cmd/server/webhook_test.go, openapi.yaml
Fixes: https://github.com/moov-io/ofac/issues/42
=> cmd/server: require auth token on watches 

cmd/server/download.go
Fixes: https://github.com/moov-io/ofac/issues/47
=> cmd/server: add last_ofac_data_refresh_success metric

cmd/ofactest/main.go, cmd/ofactest/oauth.go, cmd/ofactest/search.go
This relies on a [recent `apitest` change to save an OAuth token](https://github.com/moov-io/api/commit/dce7ba07ca4f421a287f2a06569befe4f8de3d6d#diff-6d11dae29e9ab088de1fc43c38d67851R152). I want to design something better, but unsure what now.
=> cmd/ofactest: initial setup testing endpoints

.travis.yml
See: https://groups.google.com/forum/#!msg/golang-announce/r0R2jijOjBo/Egi-Q4uWGQAJ
=> build: test with go1.12rc1

client/docs/Sdn.md, client/model_sdn.go, cmd/server/companies.go, cmd/server/companies_test.go, cmd/server/customers.go, cmd/server/customers_test.go, cmd/server/main.go, cmd/server/search_async.go, cmd/server/search_async_test.go, cmd/server/sqlite.go, cmd/server/watch.go, cmd/server/watch_test.go, cmd/server/webhook.go, cmd/server/webhook_test.go, openapi.yaml
Issue: https://github.com/moov-io/ofac/issues/57
=> cmd/server: implement company routes, unsafe/exception status and watches

cmd/ofactest/main.go, cmd/ofactest/search.go, cmd/ofactest/watch.go
This needs a few PR's merged first. (https://github.com/moov-io/ofac/pull/62 and https://github.com/moov-io/ofac/pull/63)
Issue: https://github.com/moov-io/ofac/issues/57
=> cmd/ofactest: test for company routes, allow custom name search param

cmd/ofactest/main.go, cmd/ofactest/main_test.go
Fixes: https://github.com/moov-io/ofac/issues/66
=> cmd/ofactest: trim extra paths from -address

cmd/server/search_handlers.go, cmd/server/search_handlers_test.go
This came up in slack that such an endpoint would be useful.
=> cmd/server: support GET /search?q=... for searching SDN names, alt names, and address field

cmd/server/search.go, cmd/server/search_test.go
'Nicolas Maduro' is listed as 'MADURO MOROS, Nicolas' in the OFAC list, but search queries would come in as 'Nicolas Maduro'. We need to re-order names so that search queries match them better.
This matches 'Nicolas Maduro' against his OFAC name at 94.4%.
=> cmd/server: re-order SDN names where surname precedes "first name"

README.md, client/README.md, client/api_ofac.go, client/docs/OFACApi.md, cmd/server/companies.go, cmd/server/customers.go, cmd/server/main.go, cmd/server/search.go, cmd/server/search_async.go, cmd/server/search_async_test.go, cmd/server/search_test.go, cmd/server/watch.go, cmd/server/watch_test.go, cmd/server/webhook_test.go, examples/webhook/webhook.go, openapi.yaml
This also includes the match percentage in the webhook body.
=> cmd/server: async: send webhooks on company/customer name watches 

README.md
See also https://github.com/moov-io/ach/pull/541
=> docs: describe moov's primary usage of OFAC (for paygate)

client/api_ofac.go, client/docs/OFACApi.md, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_handlers_test.go, openapi.yaml
Fixes: https://github.com/moov-io/ofac/issues/79
=>  cmd/server: handle city, state, providence, and zip in address search

README.md
=> Update README.md to fox port

download.go
The DPL list is flakey, so let's retry on any download.
Fixes: https://github.com/moov-io/ofac/issues/109
=> attempt retries when downloading files

client/client.go, cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
https://github.com/moov-io/ofac/issues/115 mentions how we are too eager in reporting high string similarities. This change tones down our false positives by limiting the jaro similarity to the string's ratio of lengths. 
```
$ curl -s "localhost:8084/search?q=george+w+bush&limit=2" | jq .SDNs 
[
{
"entityID": "2680",
"sdnName": "HABBASH, George",
"sdnType": "individual",
"program": "SDT",
"title": "Secretary General of POPULAR FRONT FOR THE LIBERATION OF PALESTINE",
"callSign": "",
"vesselType": "",
"tonnage": "",
"grossRegisteredTonnage": "",
"vesselFlag": "",
"vesselOwner": "",
"remarks": "Secretary General of POPULAR FRONT FOR THE LIBERATION OF PALESTINE.",
"match": 0.7445101906640368
},
{
"entityID": "18996",
"sdnName": "HASWANI, George",
"sdnType": "individual",
"program": "SYRIA", …
```
=> cmd/server: limit string similarity to their length ratio

.travis.yml
Issue: https://github.com/moov-io/infra/issues/58
=> build: download CI tools rather than install

cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
Instead of doing fancy stuff (removing spaces and tabulating our weird
average) let's try and mirror what OFAC's official search tool does
regarding jaro-winkler comparisons.
=> cmd/server: match treasury.gov match percentages

client/README.md, client/api/openapi.yaml, client/api_ofac.go, client/docs/EntityAddress.md, client/docs/OFACApi.md, client/docs/OfacCompany.md, client/docs/OfacCustomer.md, client/docs/Search.md, client/model_entity_address.go, client/model_ofac_company.go, client/model_ofac_customer.go, client/model_search.go, openapi.yaml
This was renamed as paygate (and really Moov's API) needs an Address model. Sorry for the breaking change
=> api,client: rename Address to EntiyAddress

cmd/server/search_handlers.go, cmd/server/search_handlers_test.go
This will only return SDNs and Addresses where both match within the limit.
=> cmd/server: AND name and address queries if params are provided

go.mod, go.sum
Fixes: https://github.com/moov-io/ofac/issues/167
=> build: update go4.org module version

cmd/server/filter.go, cmd/server/filter_test.go, cmd/server/values.go, cmd/server/values_test.go, openapi.yaml
Fixes: https://github.com/moov-io/watchman/issues/177
=> cmd/server: add special case 'entity' for sdnType filter

cmd/server/search_csl_test.go, pkg/csl/download.go, pkg/csl/download_test.go
Minor cleanup from https://github.com/moov-io/watchman/pull/197
=> csl: share and export TRADEGOV_API_KEY env var value

.travis.yml, cmd/server/companies_test.go, cmd/server/customers_test.go, cmd/server/download.go, cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, cmd/server/stopwords.go, cmd/server/stopwords_test.go, go.mod, go.sum
Fixes: https://github.com/moov-io/watchman/issues/176 
This change uses:
- https://godoc.org/github.com/abadojack/whatlanggo
- https://godoc.org/github.com/pariz/gountries
=> cmd/server: remove stopwords after detecting an SDN name's language

cmd/server/companies_test.go, cmd/server/customers_test.go, cmd/server/download.go, cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
Issue: https://github.com/moov-io/watchman/issues/204
=> cmd/server: don't remove stopwords from alt names or individual SSI's

cmd/server/search.go, cmd/server/search_test.go
A query like: ?q=24 incorrectly matches against a partial remarks ID from SDN 23410.
Fixes: https://github.com/moov-io/watchman/issues/211
=> cmd/server: match remark ID's exactly in all cases

cmd/server/main.go
Issue: https://github.com/moov-io/watchman/issues/214
=> cmd/server: clarify shutdown logging

cmd/server/download.go, pkg/ofac/reader.go, pkg/ofac/reader_test.go
Fixes: https://github.com/moov-io/watchman/issues/248
=> ofac: allow unescaped inner quotes in SDN comments records

Dockerfile-static, README.md, makefile
Issue: https://github.com/moov-io/customers/issues/71
=> build: add moov/watchman:static image for better test instances

cmd/server/issue115_test.go, cmd/server/search.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go, go.mod, go.sum
See: https://github.com/xrash/smetrics/issues/7
=> search: upgrade smetrics with fixed Jaro implementation 

cmd/server/webhook.go, cmd/server/webhook_test.go
Fixes: https://github.com/moov-io/watchman/issues/289
=> webhooks: handle nil Response without a panic

cmd/server/search_async.go
Reported by @swhyte-rt. Thanks!
=> search: reference appropriate SDN for webhook body

README.md
Issue: https://github.com/moov-io/watchman/issues/294
=> docs: re-order "getting started" to suggest docker image

cmd/server/search_async.go
Fixes: https://github.com/moov-io/watchman/issues/292
=> search: skip calling webhooks if we don't render a body

webui/src/Form/data.js, webui/src/Form/index.js, webui/src/Form/options.js
Fixes: https://github.com/moov-io/watchman/issues/308
=> webui: fix Country "All" value so it's not passed through to query params

cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_handlers_test.go, cmd/server/search_test.go
Fixes: https://github.com/moov-io/watchman/issues/309
=> search: filter countries rather than rank, OR NameAndAddress results

cmd/server/download.go
Docs: https://github.com/moov-io/watchman/blob/master/docs/metrics.md#last-data-refresh-failure
=> server: add last_data_refresh_failure metric

README.md, docs/README.md, docs/file-structure.md, docs/ha.md, docs/metrics.md, docs/pipeline.md, docs/runbook.md, docs/search.md, docs/webui.md
Fixed a few things I missed during my initial readme update, as well as typos and formatting issues in other docs.
=> Minor improvements to docs

go.mod, go.sum, pkg/csl/el.go, pkg/csl/reader.go, pkg/csl/reader_test.go
Issue: https://github.com/moov-io/watchman/issues/326
=> csl: fix parsing with newer CSV format

api/client.yaml, client/api/openapi.yaml, client/api_watchman.go, client/docs/WatchmanApi.md, cmd/batchsearch/main.go, cmd/server/companies.go, cmd/server/customers.go, cmd/server/download.go, cmd/server/download_test.go, cmd/server/sdn.go, cmd/server/search_handlers.go, cmd/watchmantest/main.go, cmd/watchmantest/search.go, cmd/watchmantest/watch.go
Issue: https://github.com/moov-io/watchman/issues/346
=> cmd/server: remove unneeded X-User-ID HTTP headers

api/client.yaml, client/api/openapi.yaml, client/api_watchman.go, client/docs/WatchmanApi.md, cmd/server/issue115_test.go, cmd/server/largest.go, cmd/server/largest_test.go, cmd/server/search.go, cmd/server/search_async.go, cmd/server/search_benchmark_test.go, cmd/server/search_handlers.go, cmd/server/search_test.go, go.mod, go.sum
Issue: https://github.com/moov-io/watchman/issues/330
=> cmd/server: add minMatch query param for searching

README.md
'pring' to 'print'
communicated to communication
ran to run
intutive to intuitive
=> Grammar and spelling updates

README.md, cmd/server/download_handler.go, cmd/server/download_handler_test.go, cmd/server/download_webhook.go, cmd/server/main.go, cmd/server/main_test.go, cmd/server/search_async.go, cmd/server/webhook.go, cmd/server/webhook_test.go
Fixes: https://github.com/moov-io/watchman/issues/412
=> cmd/server: add an optional webhook to be notified of data downloads

cmd/server/download.go, cmd/server/pipeline.go, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_us_csl.go, pkg/csl/csl.go, pkg/csl/reader.go, pkg/csl/reader_test.go, webui/package-lock.json
- Updated model to process UVL data from the core US Sanctions CSV
=> Adding Unverified List (UVL) data into Watchman search

cmd/server/download.go, cmd/server/main.go, cmd/server/pipeline.go, cmd/server/search.go, cmd/server/search_handlers.go, cmd/server/search_us_csl.go, pkg/csl/csl.go, pkg/csl/reader.go, pkg/csl/reader_test.go, webui/package-lock.json
This PR aims to implement the following fixes into Watchman:
#415 #416 #417 #418 #419 #422
=> Adding the rest of the US CSL data into Watchman to be searchable

cmd/server/download.go, cmd/server/download_webhook.go, pkg/download/client.go
Fixes: https://github.com/moov-io/watchman/issues/484
=> fix: stop setting level=error for info logs

cmd/server/search_handlers.go
Fixes: https://github.com/moov-io/watchman/issues/488
=> fix: remove logging of search queries

docs/model-validation.md
The link went to a page no longer working, updating to go correctly to the page.
=> Update model-validation.md -- fix link to FAQ

cmd/server/largest.go, cmd/server/search.go, cmd/server/search_benchmark_test.go, cmd/server/search_generic.go, cmd/server/search_test.go
Fixes: https://github.com/moov-io/watchman/issues/584
=> cmd/server: copy from largest results

pkg/download/client.go, pkg/download/client_test.go, pkg/sources/csl_eu/download_eu.go, pkg/sources/csl_uk/download_uk.go, pkg/sources/csl_us/download.go, pkg/sources/ofac/download.go
Issue: https://github.com/moov-io/watchman/issues/623
=> download: read DOWNLOAD_TIMEOUT from environment, otherwise 45s

docs/api.yaml, internal/search/api_search.go, internal/stringscore/jaro_winkler_comparison_test.go, pkg/search/client.go, pkg/search/models.go, pkg/search/models_test.go, pkg/search/similarity_address.go, pkg/search/similarity_address_test.go, pkg/search/similarity_fuzzy_test.go
Fixes: https://github.com/moov-io/watchman/issues/625
=> search: normalize addresses to improve search results, return original query

docs/_data/docs-menu.yml, docs/ingest.md, internal/ingest/api_ingest.go, internal/ingest/api_ingest_test.go, internal/ingest/service.go, internal/ingest/service_test.go, internal/search/service.go, pkg/search/client.go, pkg/search/client_test.go, pkg/search/mock_client.go
Issue: https://github.com/moov-io/watchman/issues/609
=> ingest: files add entities to the in-memory index

internal/api/url.go, internal/search/api_search.go, internal/search/api_search_test.go, pkg/search/client.go, pkg/sources/display/display_test.go
Fixes: https://github.com/moov-io/watchman/issues/635
=> search: read/write GovernmentIDs
